# Generated by Django 4.2.6 on 2023-10-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 100 символов', max_length=150, verbose_name='Название')),
                ('named_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберете пункт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.menumodel', verbose_name='Родитель')),
            ],
        ),
    ]
